air_threshold: 0.05
batch_size: 1
data: C258_3d
densification_interval: 100
densify_from_iter: 0
densify_until_iter: 15000
display_image_num: 8
do_density_control: true
image_save_iter: 2000
img_path: ./data/AAPM-chest(512)/C258_3d.npz
img_size:
- 80
- 256
- 256
ini_intensity: 0.25
ini_sigma: 0.15
start: 0.15
low_reso_stage: 5000
log_iter: 100
max_gaussians: 300000
max_grad: 1.0e-05
max_iter: 15000
min_intensity: 0.0001
num_gaussian: 50000
num_proj: 20
proj_size:
- 512
- 800
sigma_extent: 2
spatial_lr_scale: 1
tv_weight: 0.0
val_iter: 100